FROM alpine:latest as tmp

ARG JENA_VERSION=6.0.0

RUN apk add curl && \
	curl -fLo "apache-jena-${JENA_VERSION}.tar.gz" "https://dlcdn.apache.org/jena/binaries/apache-jena-${JENA_VERSION}.tar.gz" && \
	curl -fLo "apache-jena-fuseki-${JENA_VERSION}.tar.gz" "https://dlcdn.apache.org/jena/binaries/apache-jena-fuseki-${JENA_VERSION}.tar.gz" && \
	mkdir -p /opt/app && \
	tar -x -C /opt/app -f "apache-jena-${JENA_VERSION}.tar.gz" && \
	tar -x -C /opt/app -f "apache-jena-fuseki-${JENA_VERSION}.tar.gz" && \
	mv /opt/app/apache-jena-${JENA_VERSION} /opt/app/apache-jena && \
	mv /opt/app/apache-jena-fuseki-${JENA_VERSION} /opt/app/apache-jena-fuseki

FROM eclipse-temurin:25-jre-alpine

COPY --from=tmp /opt/app /opt/app
COPY entrypoint /opt/app/
COPY fuseki.ttl /opt/app/

RUN mkdir /data

WORKDIR /opt/app
CMD ["sh", "entrypoint"]
