#!/bin/sh
rm -rf db/ run/ \
 && apache-jena-4.3.1/bin/tdb2.tdbloader --loc db /data/*.ttl \
 && mkdir run/luceneIndexing -p \
 && java -Xmx16G -cp apache-jena-fuseki-4.3.1/fuseki-server.jar jena.textindexer --desc=fuseki.ttl \
 && apache-jena-fuseki-4.3.1/fuseki-server --config=fuseki.ttl
