#!/bin/sh
rm -rf db/ run/ \
 && apache-jena/bin/tdb2.tdbloader --loc db /data/*.ttl \
 && mkdir run/luceneIndexing -p \
 && java -Xmx16G -cp apache-jena-fuseki/fuseki-server.jar jena.textindexer --desc=fuseki.ttl \
 && apache-jena-fuseki/fuseki-server --config=fuseki.ttl
