# pull official base image
FROM node:24-alpine AS builder

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH=/app/node_modules/.bin:$PATH
ENV VITE_FUSEKI_URL=/fuseki/tdb2-database/query
ENV VITE_PDF_URL=/resources/pdf/
ENV VITE_SVG_URL=/resources/svg/

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm ci
# add app
COPY public/ /app/public
COPY src/ /app/src
COPY tsconfig.json /app/
COPY vite.config.ts /app/
COPY index.html /app/index.html
RUN  tsc && vite build --base ./

FROM caddy:2-alpine

RUN apk add gettext-envsubst
COPY --from=builder /app/dist/ /srv
RUN mv /srv/index.html /srv/index.html.template
COPY Caddyfile /etc/caddy/Caddyfile
COPY entrypoint.sh /bin/entrypoint.sh
ENV HTML_TITLE="Monodi viewer"
ENV BASE_PATH=""
ENV FUSEKI_HOST="fuseki"

ENTRYPOINT ["/bin/entrypoint.sh"]
CMD [ "caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile" ]
